# -*- coding: utf-8 -*-
"""Copy of Sample ML Submission Template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Bh7Bq2FRwu33TmSzwoid_AYQKYQRT8T

# **Project Name**    - Customer Satisfaction Prediction using Machine Learning

##### **Project Type**    - Classification
##### **Contribution**    - Individual

# **Project Summary -**

This project focuses on analyzing and predicting customer satisfaction (CSAT) for Flipkart’s customer support operations using machine learning techniques. In the highly competitive e-commerce industry, delivering efficient and high-quality customer support is critical for customer retention and brand loyalty. The objective of this project is to identify the key factors influencing customer satisfaction and build a predictive model that can help proactively detect dissatisfied customers.

The dataset contains detailed information about customer support interactions, including communication channel, issue category, agent hierarchy, handling time, response timestamps, product details, and CSAT scores. The analysis began with comprehensive data understanding and cleaning, where missing values, data types, and structural consistency were carefully examined. Exploratory Data Analysis (EDA) was performed to uncover patterns and relationships between variables and customer satisfaction.

Several important insights were discovered during EDA. It was observed that response time and connected handling time significantly impact customer satisfaction. Support channel performance and agent tenure also showed meaningful variation in CSAT outcomes. Additionally, certain issue categories and product segments were associated with relatively lower satisfaction levels, indicating potential service gaps.

Feature engineering was applied to enhance the dataset, including datetime processing and preparation of modeling-ready features. The CSAT score was conditioned into a classification-friendly format to support supervised machine learning. Appropriate preprocessing steps such as encoding and handling class imbalance were planned to ensure robust model performance.

The project aims to build a classification model capable of predicting customer satisfaction levels based on historical interaction data. Such a model can help Flipkart proactively identify at-risk customers, optimize support operations, and improve service quality. From a business perspective, the insights derived from this analysis can guide targeted agent training, better workload management, and faster issue resolution strategies.

Overall, this project demonstrates how data-driven decision-making and machine learning can be leveraged to enhance customer experience in e-commerce support systems. Implementing these insights can help Flipkart improve customer retention, strengthen brand trust, and achieve operational excellence in customer service.

# **GitHub Link -**

**Provide your GitHub Link here:-** https://github.com/TusharGupta74

# **Problem Statement**

Flipkart aims to improve its customer support experience by understanding the factors that influence customer satisfaction. The objective of this project is to analyze customer support interaction data and build a machine learning classification model that can predict customer satisfaction (CSAT) based on various operational and interaction-related features. This will help the business proactively identify dissatisfied customers and take corrective actions to enhance service quality and customer retention.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 15 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]





6. You may add more ml algorithms for model creation. Make sure for each and every algorithm, the following format should be answered.


*   Explain the ML Model used and it's performance using Evaluation metric Score Chart.


*   Cross- Validation & Hyperparameter Tuning

*   Have you seen any improvement? Note down the improvement with updates Evaluation metric Score Chart.

*   Explain each evaluation metric's indication towards business and the business impact pf the ML model used.

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Import Libraries

import pandas as pd
import numpy as np


import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

"""### Dataset Loading"""

# Load Dataset
from google.colab import files
uploaded = files.upload()

"""### Dataset First View"""

# Dataset First Look
df = pd.read_csv('Customer_support_data.csv')

# Displaying first 5 rows of the Data.
display(df.head())

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
print("Shape of dataset:", df.shape)

"""### Dataset Information"""

# Dataset Info
df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
duplicate_count = df.duplicated().sum()
print(f"Total duplicate records in dataset: {duplicate_count}")

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
missing_values = df.isnull().sum().sort_values(ascending=False)
missing_values

# Visualizing the missing values
plt.figure(figsize=(12,6))
sns.heatmap(df.isnull(), cbar=False)
plt.title("Missing Values Heatmap")
plt.show()

"""### What did you know about your dataset?

The dataset contains customer support interaction data from Flipkart, including details about customer queries, support channels, agent hierarchy, timestamps of issue handling, and the CSAT (Customer Satisfaction) score.

The target variable in the dataset is the CSAT Score, which represents customer satisfaction levels. The dataset includes both categorical and numerical features and contains a large number of records, making it suitable for classification modeling.

Initial inspection shows that while the dataset has no duplicate records, several columns contain missing values that will require appropriate preprocessing during the data cleaning stage.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
print("Columns in dataset:")
for col in df.columns:
    print(col)

# Dataset Describe
df.describe(include='object')

"""### Variables Description

The dataset consists of multiple variables related to customer support interactions at Flipkart. It includes information about the communication channel, issue category and sub-category, customer remarks, order details, timestamps of issue reporting and response, customer location, product details, and agent hierarchy such as agent name, supervisor, manager, tenure bucket, and shift. The target variable in this dataset is the CSAT Score, which represents the level of customer satisfaction. These variables together help in analyzing the key drivers affecting customer satisfaction and will be used for further preprocessing, feature engineering, and classification modeling.

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
unique_counts = pd.DataFrame({
    'Column': df.columns,
    'Unique_Values': [df[col].nunique() for col in df.columns]
})

unique_counts.sort_values(by='Unique_Values', ascending=False)

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.

# 1️⃣ created copy
df_clean = df.copy()

# 2️⃣ Standardize column names
df_clean.columns = df_clean.columns.str.strip().str.lower().str.replace(" ", "_")

# 3️⃣ Convert datetime columns
date_cols = [
    'order_date_time',
    'issue_reported_at',
    'issue_responded',
    'survey_response_date'
]

for col in date_cols:
    if col in df_clean.columns:
        df_clean[col] = pd.to_datetime(df_clean[col], errors='coerce')

# 4️⃣ Checking result
df_clean.info()

"""### What all manipulations have you done and insights you found?

Created a copy of the original dataset to avoid modifying the raw data.

Standardized column names by converting them to lowercase and replacing spaces with underscores for consistency.

Converted relevant date columns into datetime format to enable time-based analysis and feature engineering.

Performed an initial structural check using .info() to verify data types and identify missing values.

Observed that the dataset contains several columns with missing values, which will require proper treatment in later stages.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

# Chart - 1 visualization code
plt.figure(figsize=(8,5))
sns.countplot(x=df_clean['csat_score'])
plt.title("Distribution of CSAT Score")
plt.xlabel("CSAT Score")
plt.ylabel("Count")
plt.show()

"""##### 1. Why did you pick the specific chart?

**Answer:-** A count plot was selected to visualize the distribution of the CSAT Score because the target variable is categorical in nature. This chart clearly shows the frequency of each satisfaction level, making it easy to identify class imbalance and overall customer sentiment.

##### 2. What is/are the insight(s) found from the chart?

**Answer:-** The chart shows how customer satisfaction is distributed across different CSAT scores. It helps in identifying whether most customers are satisfied or dissatisfied and whether the dataset is imbalanced. This insight is crucial for selecting the appropriate modeling and evaluation strategy.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Answer:-** Yes, these insights help the business understand overall customer sentiment. If dissatisfaction levels are high, Flipkart can focus on improving support quality, reducing response time, and training agents. This can lead to improved customer experience, higher retention, and stronger brand loyalty.

⚠️ Negative growth insight

If the chart shows a significant number of low CSAT scores, it indicates potential service gaps. Persistent low satisfaction may lead to customer churn, negative word-of-mouth, and reduced customer lifetime value, which can negatively impact business growth. Therefore, identifying and addressing the root causes is critical.

#### Chart - 2
"""

# Chart - 2 visualization code
plt.figure(figsize=(10,6))
sns.countplot(data=df_clean, x='channel_name', hue='csat_score')
plt.title("CSAT Score Distribution Across Channels")
plt.xlabel("Channel Name")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

"""##### 1. Why did you pick the specific chart?

**Answer:-** This chart was chosen to examine the relationship between customer satisfaction (CSAT Score) and the support channel used by customers. A count plot with hue helps compare satisfaction levels across different channels and highlights performance differences clearly.

##### 2. What is/are the insight(s) found from the chart?

**Answer:-** The chart indicates that customer satisfaction varies across different support channels. Some channels show a higher concentration of high CSAT scores, suggesting better service effectiveness, while others have relatively lower satisfaction levels, indicating potential service gaps.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Answer:-** Yes, these insights can help Flipkart identify which support channels are performing well and which require improvement. By focusing on underperforming channels through better training, faster response times, or process optimization, Flipkart can enhance customer experience, improve CSAT scores, and increase customer retention.

⚠️ Negative growth insight

If certain support channels consistently produce lower CSAT scores, it indicates poor customer experience in those channels. If this issue is not addressed, it may lead to customer dissatisfaction, reduced trust in

#### Chart - 3
"""

# Chart - 3 visualization code
plt.figure(figsize=(10,6))
sns.boxplot(data=df_clean, x='csat_score', y='connected_handling_time')
plt.title("Impact of Handling Time on CSAT Score")
plt.xlabel("CSAT Score")
plt.ylabel("Connected Handling Time")
plt.show()

"""##### 1. Why did you pick the specific chart?

**Answer Here:-** This box plot was selected to analyze the relationship between connected handling time and the CSAT score. It effectively shows the distribution, spread, and outliers of handling time across different satisfaction levels, helping to understand whether resolution time impacts customer satisfaction.

##### 2. What is/are the insight(s) found from the chart?

**Answer Here:-** The visualization indicates that handling time varies across different CSAT scores. Lower satisfaction scores tend to be associated with higher or more inconsistent handling times, suggesting that delays in resolving customer issues may negatively affect customer satisfaction.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Answer Here:-** Yes, these insights can help Flipkart improve operational efficiency. By monitoring and reducing excessive handling times, the company can enhance customer experience, improve CSAT scores, and strengthen customer loyalty.

⚠️ Negative growth insight

If longer handling times consistently lead to lower CSAT scores, it indicates inefficiencies in the customer support process. If not addressed, slow issue resolution may frustrate customers, increase dissatisfaction, and potentially lead to higher customer churn, negatively impacting business growth.

#### Chart - 4
"""

# Chart - 4 visualization code
plt.figure(figsize=(10,6))
sns.countplot(data=df_clean, x='tenure_bucket', hue='csat_score')
plt.title("Customer Satisfaction across Agent Tenure")
plt.xlabel("Tenure Bucket")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

"""##### 1. Why did you pick the specific chart?

**Answer Here:-** This chart was chosen to analyze how agent experience (tenure bucket) influences customer satisfaction. Understanding this relationship helps evaluate whether more experienced agents deliver better customer service.

##### 2. What is/are the insight(s) found from the chart?

**Answer Here:-** The chart shows variation in CSAT scores across different tenure buckets. Agents with higher tenure appear to handle customer issues more effectively, resulting in relatively higher satisfaction levels compared to less experienced agents.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Answer Here:-** These insights can help Flipkart design targeted training programs for new agents and leverage experienced agents for complex cases. Improving agent capability can lead to higher CSAT scores and better customer retention.

⚠️ Negative growth insight

If lower-tenure agents consistently show lower CSAT scores, it indicates a training or onboarding gap. If not addressed, inexperienced handling may lead to poor customer experience and increased dissatisfaction.

#### Chart - 5
"""

# Chart - 5 visualization code
plt.figure(figsize=(12,6))
sns.countplot(data=df_clean, x='category', hue='csat_score')
plt.title("Customer Satisfaction across Issue Categories")
plt.xlabel("Issue Category")
plt.ylabel("Count")
plt.xticks(rotation=60)
plt.show()

"""##### 1. Why did you pick the specific chart?

**Answer Here:-** This chart was selected to understand how customer satisfaction varies across different issue categories. It helps identify which types of customer problems are associated with lower satisfaction levels.

##### 2. What is/are the insight(s) found from the chart?

**Answer Here:-** The visualization shows that CSAT scores differ across issue categories. Certain categories have relatively higher low-CSAT cases, indicating that customers facing those issues are less satisfied. This suggests that some problem areas may require process improvements.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Answer Here:-** These insights can help Flipkart prioritize improvement efforts in the most problematic issue categories. By addressing the root causes in low-performing categories, the company can enhance customer experience and improve overall satisfaction levels.

⚠️ Negative growth insight

If specific issue categories consistently produce lower CSAT scores, it indicates unresolved pain points in the customer journey. If not addressed, repeated negative experiences in these categories may lead to customer frustration, reduced trust, and potential churn.

#### Chart - 6
"""

# Chart - 6 visualization code
plt.figure(figsize=(10,5))
sns.histplot(df_clean['item_price'], bins=50, kde=True)
plt.title("Distribution of Item Price")
plt.xlabel("Item Price")
plt.ylabel("Frequency")
plt.show()

"""##### 1. Why did you pick the specific chart?

**Answer Here:-** A histogram was selected to understand the distribution of item prices in the dataset. This helps identify the spread, skewness, and concentration of order values, which may influence customer satisfaction expectations.

##### 2. What is/are the insight(s) found from the chart?

**Answer Here:-** The distribution indicates that most orders fall within a specific price range, with fewer high-value purchases. This suggests that the majority of customer interactions are related to moderately priced products, while premium orders form a smaller segment.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Answer Here:-** Understanding price distribution helps Flipkart tailor support strategies for different customer segments. High-value customers may require priority support, and identifying such segments can improve customer experience and retention.

⚠️ Negative growth insight

If high-value orders are associated with lower satisfaction (to be validated in further analysis), it may indicate unmet expectations among premium customers. This could lead to higher churn among valuable customers if not addressed.

#### Chart - 7
"""

# Chart - 7 visualization code
top_cities = df_clean['customer_city'].value_counts().head(10)

plt.figure(figsize=(10,6))
sns.barplot(x=top_cities.values, y=top_cities.index)
plt.title("Top 10 Customer Cities by Support Requests")
plt.xlabel("Number of Requests")
plt.ylabel("Customer City")
plt.show()

"""##### 1. Why did you pick the specific chart?

**Answer Here:-** This chart was selected to identify the top cities generating the highest number of customer support requests. Understanding geographic concentration helps in resource planning and regional service optimization.

##### 2. What is/are the insight(s) found from the chart?

**Answer Here:-** The visualization shows that customer support requests are concentrated in a few major cities. This indicates higher platform usage and support demand from these regions, suggesting the need for focused service management in high-volume locations.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Answer Here:-** These insights enable Flipkart to allocate support resources more efficiently in high-demand cities, improve response times, and enhance regional customer experience. Targeted improvements in major cities can significantly boost overall satisfaction.

⚠️ Negative growth insight

If certain high-volume cities also show lower satisfaction levels (to be validated later), it may indicate regional service bottlenecks. Ignoring such hotspots could lead to concentrated customer dissatisfaction and negative brand perception in key markets.

#### Chart - 8
"""

# Chart - 8 visualization code
df_clean['response_time_mins'] = (
    df_clean['issue_responded'] - df_clean['issue_reported_at']
).dt.total_seconds() / 60


plt.figure(figsize=(10,6))
sns.boxplot(data=df_clean, x='csat_score', y='response_time_mins')
plt.title("Response Time Impact on Customer Satisfaction")
plt.xlabel("CSAT Score")
plt.ylabel("Response Time (minutes)")
plt.show()

"""##### 1. Why did you pick the specific chart?

**Answer Here:-** This chart was selected to examine how response time affects customer satisfaction. A box plot helps visualize the distribution and variability of response times across different CSAT levels, making it easier to detect performance patterns.

##### 2. What is/are the insight(s) found from the chart?

**Answer Here:-** The chart suggests that longer response times are generally associated with lower CSAT scores. Faster responses tend to correspond with higher customer satisfaction, indicating the importance of quick issue handling.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Answer Here:-** These insights highlight the importance of reducing response time in customer support operations. By improving response speed, Flipkart can enhance customer experience, increase satisfaction levels, and strengthen customer loyalty.

⚠️ Negative growth insight

If response times remain high for a significant number of cases, it indicates operational inefficiencies in the support workflow. Prolonged delays may frustrate customers and increase the risk of dissatisfaction and churn.

#### Chart - 9
"""

# Chart - 9 visualization code
plt.figure(figsize=(10,6))
sns.countplot(data=df_clean, x='agent_shift', hue='csat_score')
plt.title("Customer Satisfaction across Agent Shifts")
plt.xlabel("Agent Shift")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

"""##### 1. Why did you pick the specific chart?

**Answer Here:-** This chart was chosen to analyze how customer satisfaction varies across different agent work shifts. It helps evaluate whether service quality differs by shift and identifies potential operational gaps.

##### 2. What is/are the insight(s) found from the chart?

**Answer Here:-** The visualization indicates variation in CSAT scores across different agent shifts. Certain shifts appear to have relatively higher low-CSAT cases, suggesting possible workload pressure or staffing challenges during those periods.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Answer Here:-** These insights can help Flipkart optimize workforce allocation across shifts. By strengthening staffing and monitoring performance in weaker shifts, the company can improve service consistency and overall customer satisfaction.

⚠️ Negative growth insight

If a particular shift consistently shows lower CSAT scores, it may indicate understaffing, higher workload, or performance gaps during that time window. Ignoring this issue could lead to repeated poor customer experiences and potential customer churn.

#### Chart - 10
"""

# Chart - 10 visualization code
plt.figure(figsize=(12,6))
sns.countplot(data=df_clean, x='product_category', hue='csat_score')
plt.title("Customer Satisfaction across Product Categories")
plt.xlabel("Product Category")
plt.ylabel("Count")
plt.xticks(rotation=60)
plt.show()

"""##### 1. Why did you pick the specific chart?

**Answer Here:-** This chart was chosen to analyze how customer satisfaction varies across different product categories. It helps identify whether certain product segments are associated with more customer complaints or lower satisfaction levels.

##### 2. What is/are the insight(s) found from the chart?

**Answer Here:-** The chart shows that CSAT scores vary across product categories. Some categories have relatively higher low-CSAT cases, indicating potential product or service issues in those segments. This suggests that customer experience is not uniform across all product types.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Answer Here:-** These insights help Flipkart focus on improving customer experience in low-performing product categories. By addressing product quality issues, delivery problems, or support gaps in specific categories, the company can improve overall customer satisfaction and retention.

⚠️ Negative growth insight

If certain product categories consistently show lower CSAT scores, it indicates unresolved customer pain points in those segments. If ignored, this may lead to negative reviews, reduced repeat purchases, and potential revenue loss from those categories.

#### Chart - 11
"""

# Chart - 11 visualization code
avg_csat_channel = df_clean.groupby('channel_name')['csat_score'].mean().sort_values(ascending=False)

plt.figure(figsize=(10,6))
sns.barplot(x=avg_csat_channel.values, y=avg_csat_channel.index)
plt.title("Average CSAT Score by Support Channel")
plt.xlabel("Average CSAT Score")
plt.ylabel("Channel Name")
plt.show()

"""##### 1. Why did you pick the specific chart?

**Answer Here:-** This chart was selected to compare the average customer satisfaction across different support channels. Unlike count plots, the mean CSAT view provides a clearer picture of service quality performance by channel.

##### 2. What is/are the insight(s) found from the chart?

**Answer Here:-** The chart reveals that some support channels achieve higher average CSAT scores than others, indicating better service effectiveness. Channels with lower average CSAT may require process improvements or additional agent training.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Answer Here:-** These insights help Flipkart identify high-performing and underperforming support channels. By replicating best practices from top channels and improving weaker ones, the company can enhance overall customer satisfaction and service consistency.

⚠️ Negative growth insight

If certain channels consistently show lower average CSAT scores, it indicates service quality gaps in those channels. If not addressed, customers using those channels may experience poor support, leading to dissatisfaction and potential churn.

#### Chart - 12
"""

# Chart - 12 visualization code
avg_csat_cat = (
    df_clean.groupby('category')['csat_score']
    .mean()
    .sort_values(ascending=False)
)

plt.figure(figsize=(12,6))
sns.barplot(x=avg_csat_cat.values, y=avg_csat_cat.index)

plt.title("Average CSAT Score by Issue Category")
plt.xlabel("Average CSAT Score")
plt.ylabel("Issue Category")
plt.show()

"""##### 1. Why did you pick the specific chart?

**Answer Here:-** This heatmap was selected to understand the correlation between numerical features in the dataset. It helps identify multicollinearity and reveals which variables have stronger relationships with the target variable.

##### 2. What is/are the insight(s) found from the chart?

**Answer Here:-** The heatmap shows that most numerical features have low to moderate correlation with each other, indicating limited multicollinearity. This suggests that the features can be safely used in model building without severe redundancy.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Answer Here:-** Understanding feature relationships helps in building more reliable and interpretable models. By avoiding highly correlated redundant features, Flipkart can develop more accurate customer satisfaction prediction systems.

⚠️ Negative growth insight

If strong multicollinearity exists between key numerical features, it may lead to unstable model performance and misleading interpretations. If ignored, this could reduce the reliability of customer satisfaction predictions.

#### Chart - 13
"""

# Chart - 13 visualization code
df_clean['satisfaction_flag'] = df_clean['csat_score'].apply(
    lambda x: 'Satisfied' if x >= 4 else 'Unsatisfied'
)


plt.figure(figsize=(6,4))
sns.countplot(data=df_clean, x='satisfaction_flag')
plt.title("Satisfied vs Unsatisfied Customers")
plt.xlabel("Customer Satisfaction")
plt.ylabel("Count")
plt.show()

"""##### 1. Why did you pick the specific chart?

**Answer Here:-** This chart was chosen to visualize the overall distribution of satisfied versus unsatisfied customers. It simplifies the multi-level CSAT score into a business-friendly binary view and helps assess class imbalance for the classification model.

##### 2. What is/are the insight(s) found from the chart?

**Answer Here:-** The chart shows the proportion of satisfied and unsatisfied customers in the dataset. It indicates whether customer sentiment is largely positive or if a significant portion of customers are dissatisfied, which is important for modeling strategy.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Answer Here:-** This insight helps Flipkart quickly understand overall customer sentiment. If dissatisfaction is significant, targeted service improvements can be implemented to enhance customer experience and retention.

⚠️ Negative growth insight

If the unsatisfied customer segment is large, it signals potential service gaps. If not addressed, persistent dissatisfaction may lead to customer churn, negative reviews, and reduced brand loyalty.

#### Chart - 14 - Correlation Heatmap
"""

# Correlation Heatmap visualization code
plt.figure(figsize=(10,6))

# select numerical columns
num_cols = df_clean.select_dtypes(include=[np.number])

sns.heatmap(num_cols.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title("Correlation Heatmap of Numerical Features")
plt.show()

"""##### 1. Why did you pick the specific chart?

**Answer Here:-** This chart was selected to compare the average customer satisfaction across different issue categories. It provides a clearer quality comparison and helps identify which categories are associated with better or worse customer experience.

##### 2. What is/are the insight(s) found from the chart?

**Answer Here:-** The chart shows variation in average CSAT scores across issue categories. Some categories demonstrate higher customer satisfaction, while others lag behind, indicating potential service or process issues in those areas.

#### Chart - 15 - Pair Plot
"""

# Pair Plot visualization code
pair_cols = ['csat_score', 'item_price', 'connected_handling_time']

temp_df = df_clean[pair_cols].dropna()

sample_size = min(2000, len(temp_df))  # safe sample size

sample_df = temp_df.sample(sample_size, random_state=42)

sns.pairplot(sample_df)
plt.suptitle("Pair Plot of Key Numerical Features", y=1.02)
plt.show()

"""##### 1. Why did you pick the specific chart?

**Answer Here:-**  A pair plot was selected to visualize the pairwise relationships and distributions among key numerical features in the dataset. It helps in identifying potential correlations, patterns, and outliers that may influence customer satisfaction. This visualization also supports better feature understanding before building the machine learning model. Here.

##### 2. What is/are the insight(s) found from the chart?

**Answer Here:-** The pair plot indicates that most numerical variables show weak to moderate relationships with the CSAT score. The distributions appear slightly skewed, and a few outliers are visible in handling time and item price. This suggests that customer satisfaction is likely influenced by multiple factors rather than a single dominant numerical feature.

## ***5. Hypothesis Testing***

### Based on your chart experiments, define three hypothetical statements from the dataset. In the next three questions, perform hypothesis testing to obtain final conclusion about the statements through your code and statistical testing.

**Answer Here:-**

Hypothesis 1:
There is a significant relationship between connected handling time and customer satisfaction (CSAT score).

Hypothesis 2:
Customer satisfaction varies significantly across different support channels.

Hypothesis 3:
Agent tenure bucket has a significant impact on customer satisfaction levels.

### Hypothetical Statement - 1

#### 1. State Your research hypothesis as a null hypothesis and alternate

✅ Research Hypothesis

Null Hypothesis (H₀):
There is no significant difference in connected handling time between satisfied and unsatisfied customers.

Alternate Hypothesis (H₁):
There is a significant difference in connected handling time between satisfied and unsatisfied customers.

#### 2. Perform an appropriate statistical test.
"""

# Perform Statistical Test to obtain P-Value
from scipy.stats import ttest_ind

# Create satisfaction flag if not exists
df_clean['satisfaction_flag'] = df_clean['csat_score'].apply(
    lambda x: 'Satisfied' if x >= 4 else 'Unsatisfied'
)

# Separate groups
satisfied = df_clean[df_clean['satisfaction_flag'] == 'Satisfied']['connected_handling_time'].dropna()
unsatisfied = df_clean[df_clean['satisfaction_flag'] == 'Unsatisfied']['connected_handling_time'].dropna()

# Perform Independent T-test
t_stat, p_value = ttest_ind(satisfied, unsatisfied, equal_var=False)

print("T-statistic:", t_stat)
print("P-value:", p_value)

"""Which statistical test have you done to obtain P-Value?

**Answer Here:-** An Independent Two-Sample t-test was performed to compare the mean connected handling time between satisfied and unsatisfied customer groups.

##### Why did you choose the specific statistical test?

**Answer Here:-** The Independent t-test was chosen because the analysis compares the mean of a continuous variable (connected handling time) between two independent groups (satisfied vs unsatisfied customers). This test is appropriate for determining whether the difference in means is statistically significant.

### Hypothetical Statement - 2

#### 1. State Your research hypothesis as a null hypothesis and alternate hypothesis.

**Answer Here:-** Research Hypothesis

Null Hypothesis (H₀):
There is no significant difference in connected handling time between satisfied and unsatisfied customers.

Alternate Hypothesis (H₁):
There is a significant difference in connected handling time between satisfied and unsatisfied customers.

#### 2. Perform an appropriate statistical test.
"""

# Perform Statistical Test to obtain P-Value

from scipy.stats import ttest_ind

# Create satisfaction flag
df_clean['satisfaction_flag'] = df_clean['csat_score'].apply(
    lambda x: 'Satisfied' if x >= 4 else 'Unsatisfied'
)

# Separate the groups
satisfied = df_clean[df_clean['satisfaction_flag'] == 'Satisfied']['connected_handling_time'].dropna()
unsatisfied = df_clean[df_clean['satisfaction_flag'] == 'Unsatisfied']['connected_handling_time'].dropna()

# Perform Independent T-test
t_stat, p_value = ttest_ind(satisfied, unsatisfied, equal_var=False)

print("T-statistic:", t_stat)
print("P-value:", p_value)

"""##### Which statistical test have you done to obtain P-Value?

**Answer Here:-** An Independent Two-Sample t-test was performed to obtain the p-value.

##### Why did you choose the specific statistical test?

**Answer Here:-** The Independent Two-Sample t-test was chosen because it compares the mean of a continuous variable (connected handling time) between two independent groups (satisfied and unsatisfied customers). This test helps determine whether the difference in their average handling time is statistically significant.

### Hypothetical Statement - 3

#### 1. State Your research hypothesis as a null hypothesis and alternate hypothesis.

**Answer Here:-** Research Hypothesis

Null Hypothesis (H₀):
Customer satisfaction is independent of the agent tenure bucket. There is no significant association between agent tenure and CSAT score.

Alternate Hypothesis (H₁):
Customer satisfaction is dependent on the agent tenure bucket. There is a significant association between agent tenure and CSAT score.

#### 2. Perform an appropriate statistical test.
"""

# Perform Statistical Test to obtain P-Value
from scipy.stats import chi2_contingency

# Create satisfaction flag if not already created
df_clean['satisfaction_flag'] = df_clean['csat_score'].apply(
    lambda x: 'Satisfied' if x >= 4 else 'Unsatisfied'
)

# Create contingency table
contingency_table = pd.crosstab(df_clean['tenure_bucket'], df_clean['satisfaction_flag'])

# Perform Chi-Square Test
chi2, p_value, dof, expected = chi2_contingency(contingency_table)

print("Chi-square statistic:", chi2)
print("P-value:", p_value)

"""##### Which statistical test have you done to obtain P-Value?

**Answer Here:-** A Chi-Square Test of Independence was performed to obtain the p-value.

##### Why did you choose the specific statistical test?

**Answer Here:-** The Chi-Square Test of Independence was chosen because both variables, agent tenure bucket and customer satisfaction, are categorical. This test helps determine whether there is a significant association between these two variables.

## ***6. Feature Engineering & Data Pre-processing***

### 1. Handling Missing Values
"""

# Handling Missing Values & Missing Value Imputation
# Check missing values
missing_values = df_clean.isnull().sum()
print(missing_values)

# Fill categorical columns with 'Unknown'
categorical_cols = df_clean.select_dtypes(include='object').columns

for col in categorical_cols:
    df_clean[col].fillna('Unknown', inplace=True)

# Fill numerical columns with median
numerical_cols = df_clean.select_dtypes(include=['int64','float64']).columns

for col in numerical_cols:
    df_clean[col].fillna(df_clean[col].median(), inplace=True)

# Check again
print("Missing values after imputation:")
print(df_clean.isnull().sum())

"""#### What all missing value imputation techniques have you used and why did you use those techniques?

**Answer Here:-** Missing Value Imputation Techniques Used

In this project, two main imputation techniques were used to handle missing values:

1. Categorical Variables – 'Unknown' Imputation:
Missing values in categorical columns were filled with the value 'Unknown'. This helps preserve the dataset structure without removing rows and allows the model to treat missing categories as a separate group.

2. Numerical Variables – Median Imputation:
Missing values in numerical columns were replaced with the median of the respective column. The median was chosen because it is less sensitive to outliers compared to the mean and provides a more robust estimate for skewed data.

These techniques ensure that the dataset remains complete and suitable for machine learning modeling without introducing significant bias.

### 2. Handling Outliers
"""

# Handling Outliers & Outlier treatments
import numpy as np

# Select numerical columns
num_cols = df_clean.select_dtypes(include=np.number).columns

for col in num_cols:

    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Cap the outliers
    df_clean[col] = np.where(df_clean[col] > upper_bound, upper_bound, df_clean[col])
    df_clean[col] = np.where(df_clean[col] < lower_bound, lower_bound, df_clean[col])

print("Outliers treated using IQR method.")

"""##### What all outlier treatment techniques have you used and why did you use those techniques?

**Answer Here:-** In this project, the Interquartile Range (IQR) method was used to detect and treat outliers in numerical features. Values that fell below the lower bound (Q1 − 1.5 × IQR) or above the upper bound (Q3 + 1.5 × IQR) were capped to the respective boundary values.

This technique was chosen because it is effective for identifying extreme values in skewed datasets and helps reduce the impact of outliers without removing important observations. By capping the outliers instead of deleting them, the dataset retains its size and becomes more stable for machine learning modeling.

### 3. Categorical Encoding
"""

# Encode your categorical columns
from sklearn.preprocessing import LabelEncoder

# Identify categorical columns
cat_cols = df_clean.select_dtypes(include='object').columns

# Initialize encoder
le = LabelEncoder()

# Apply encoding
for col in cat_cols:
    df_clean[col] = le.fit_transform(df_clean[col])

print("Categorical columns encoded successfully.")

"""#### What all categorical encoding techniques have you used & why did you use those techniques?

**Answer Here:-** In this project, Label Encoding was used to convert categorical variables into numerical format. Label Encoding assigns a unique numerical value to each category in a feature.

This technique was chosen because machine learning algorithms require numerical input data and cannot directly process text-based categorical variables. Label Encoding is simple, efficient, and suitable for datasets where categorical variables do not have a natural order but need to be transformed into numeric form for model training.

### 4. Textual Data Preprocessing
(It's mandatory for textual dataset i.e., NLP, Sentiment Analysis, Text Clustering etc.)

#### 1. Expand Contraction
"""

pip install contractions

# Expand Contraction
import contractions

df['Customer Remarks'] = df['Customer Remarks'].astype(str).apply(contractions.fix)

df['Customer Remarks'].head()

"""#### 2. Lower Casing"""

# Lower Casing
df.columns = df.columns.str.lower().str.replace(" ", "_")

"""#### 3. Removing Punctuations"""

df['customer_remarks'] = df['customer_remarks'].fillna('')

# Remove Punctuations
import string

df['customer_remarks'] = df['customer_remarks'].apply(
    lambda x: x.translate(str.maketrans('', '', string.punctuation))
)

df['customer_remarks'].head()

"""#### 4. Removing URLs & Removing words and digits contain digits."""

# Remove URLs & Remove words and digits contain digits
import re

df['customer_remarks'] = df['customer_remarks'].apply(
    lambda x: re.sub(r'http\S+|www\S+|https\S+', '', x)  # remove URLs
)

df['customer_remarks'] = df['customer_remarks'].apply(
    lambda x: re.sub(r'\w*\d\w*', '', x)  # remove words containing digits
)

df['customer_remarks'].head()

"""#### 5. Removing Stopwords & Removing White spaces"""

# Remove Stopwords
import nltk
from nltk.corpus import stopwords

# Download stopwords (run once)
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

# Remove stopwords
df['customer_remarks'] = df['customer_remarks'].apply(
    lambda x: ' '.join([word for word in x.split() if word not in stop_words])
)

# Remove White spaces
df['customer_remarks'] = df['customer_remarks'].str.strip()

df['customer_remarks'].head()

"""#### 6. Rephrase Text"""

# Rephrase Text
df['customer_remarks'] = df['customer_remarks'].apply(
    lambda x: ' '.join(x.split())
)

df['customer_remarks'].head()

"""#### 7. Tokenization"""

# Tokenization
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

# Tokenization

from nltk.tokenize import word_tokenize

df['tokens'] = df['customer_remarks'].apply(word_tokenize)

df[['customer_remarks','tokens']].head()

"""#### 8. Text Normalization"""

# Normalizing Text (i.e., Stemming, Lemmatization etc.)
import nltk
from nltk.stem import WordNetLemmatizer

# download wordnet (run once)
nltk.download('wordnet')
nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()

df['customer_remarks'] = df['customer_remarks'].apply(
    lambda x: ' '.join([lemmatizer.lemmatize(word) for word in x.split()])
)

df['customer_remarks'].head()

"""##### Which text normalization technique have you used and why?

**Answer Here:-** In this project, Lemmatization was used as the text normalization technique. Lemmatization converts words into their base or dictionary form, which helps standardize different variations of a word into a single meaningful representation. This technique was chosen because it preserves the actual meaning of words better than stemming and improves the quality of textual data for natural language processing and machine learning tasks.

#### 9. Part of speech tagging
"""

# POS Taging
import nltk

nltk.download('averaged_perceptron_tagger_eng')

import nltk
from nltk import pos_tag
from nltk.tokenize import word_tokenize

# download required resources
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt')

df['pos_tags'] = df['customer_remarks'].apply(
    lambda x: pos_tag(word_tokenize(x))
)

df[['customer_remarks','pos_tags']].head()

"""#### 10. Text Vectorization"""

# Vectorizing Text
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=500)

X_text = tfidf.fit_transform(df['customer_remarks'])

X_text.shape

"""##### Which text vectorization technique have you used and why?

**Answer Here:-** The TF-IDF vectorization technique was used to convert textual data into numerical vectors. TF-IDF was chosen because it captures the importance of words in a document relative to the entire dataset, giving higher weight to informative words while reducing the impact of frequently occurring but less meaningful words.

### 4. Feature Manipulation & Selection

#### 1. Feature Manipulation
"""

# Manipulate Features to minimize feature correlation and create new features
# Convert date columns to datetime if not already
date_cols = ['order_date_time', 'issue_reported_at', 'issue_responded', 'survey_response_date']

for col in date_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')


# Create Response Time Feature
df['response_time_minutes'] = (
    df['issue_responded'] - df['issue_reported_at']
).dt.total_seconds() / 60


# Create Order to Issue Reporting Time
df['order_to_issue_time'] = (
    df['issue_reported_at'] - df['order_date_time']
).dt.total_seconds() / 3600


# Drop original timestamp columns to reduce multicollinearity
df.drop(columns=date_cols, inplace=True, errors='ignore')

df.head()

"""#### 2. Feature Selection"""

# Select your features wisely to avoid overfitting
# Remove ID columns which do not help in prediction
df = df.drop(columns=['unique_id', 'order_id'], errors='ignore')

# Define target variable
y = df['csat_score']

# Define feature variables
X = df.drop(columns=['csat_score'])

# Check shape
print("Feature shape:", X.shape)
print("Target shape:", y.shape)

"""##### What all feature selection methods have you used  and why?

**Answer Here:-** In this project, manual feature selection was applied by removing irrelevant identifier columns and keeping only meaningful features related to customer interactions and support operations. This method was chosen because identifier columns such as unique IDs and order IDs do not contribute to predictive modeling and may introduce noise. Removing such features helps reduce overfitting and improves model performance.

##### Which all features you found important and why?

**Answer Here:-** Several features were found to be important for predicting customer satisfaction. These include response time, connected handling time, support channel, issue category, and agent tenure bucket. Response time and handling time reflect how quickly customer issues are resolved, which directly affects satisfaction levels. Support channel and issue category help capture the nature of customer interactions and problem types, while agent tenure indicates experience level, which may influence service quality. These features provide meaningful information about customer support performance and are likely to impact CSAT scores.

### 5. Data Transformation

#### Do you think that your data needs to be transformed? If yes, which transformation have you used. Explain Why?
"""

# Transform Your data
from sklearn.preprocessing import StandardScaler

# Select only numerical columns
X_numeric = X.select_dtypes(include=['int64','float64'])

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X_numeric)

print("Data transformation completed.")

"""### 6. Data Scaling"""

# Scaling your data

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X_numeric)

print("Data scaling completed.")

"""##### Which method have you used to scale you data and why?

**Answer Here:-** The StandardScaler method was used to scale the data. It was chosen because it standardizes numerical features by removing the mean and scaling them to unit variance. This helps ensure that all features contribute equally to the model and prevents features with larger values from dominating the learning process.

### 7. Dimesionality Reduction

##### Do you think that dimensionality reduction is needed? Explain Why?

**Answer Here:-** In this project, dimensionality reduction was not strictly required because the dataset does not contain an extremely large number of features after preprocessing and feature selection. Most of the irrelevant and redundant features were already removed during the feature selection stage. Since the remaining features are meaningful and manageable in number, applying dimensionality reduction techniques such as PCA was not necessary. Avoiding unnecessary dimensionality reduction also helps maintain the interpretability of the model.
"""

# DImensionality Reduction (If needed)

"""##### Which dimensionality reduction technique have you used and why? (If dimensionality reduction done on dataset.)

**Answer Here:-**  Dimensionality reduction was not applied in this project because the dataset contained a manageable number of features after preprocessing and feature selection. Most irrelevant and redundant variables were already removed during the feature selection stage, which reduced the risk of overfitting. Therefore, additional dimensionality reduction techniques such as PCA were not necessary, and keeping the original features helped maintain model interpretability.

### 8. Data Splitting
"""

# Split your data to train and test. Choose Splitting ratio wisely.
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

"""##### What data splitting ratio have you used and why?

**Answer Here:-** An 80:20 train-test split ratio was used in this project. This ratio is commonly used in machine learning because it provides sufficient data for training the model while keeping a reasonable portion of data for evaluating the model’s performance on unseen data.

### 9. Handling Imbalanced Dataset

##### Do you think the dataset is imbalanced? Explain Why.

**Answer Here:-** Yes, the dataset may show some imbalance in the distribution of the CSAT scores, where certain satisfaction levels appear more frequently than others. Such imbalance can affect the performance of machine learning models because the model may become biased toward the majority class and perform poorly in predicting minority classes.
"""

# Handling Imbalanced Dataset (If needed)
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')

X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

print("Original dataset shape:")
print(y_train.value_counts())

print("\nResampled dataset shape:")
print(y_resampled.value_counts())

"""##### What technique did you use to handle the imbalance dataset and why? (If needed to be balanced)

**Answer Here:-** To handle the imbalance in the dataset, the SMOTE (Synthetic Minority Oversampling Technique) method was used. SMOTE works by generating synthetic samples for the minority class instead of simply duplicating existing data points. This helps create a more balanced dataset and allows the model to learn patterns from both classes effectively.

SMOTE was chosen because it improves model performance by reducing bias toward the majority class and helps the model better predict the minority class.

## ***7. ML Model Implementation***

### ML Model - 1
"""

# ML Model - 1 Implementation
from sklearn.linear_model import LogisticRegression

# Initialize model
log_model = LogisticRegression(max_iter=1000)

# Fit the model
log_model.fit(X_resampled, y_resampled)

"""#### 1. Explain the ML Model used and it's performance using Evaluation metric Score Chart."""

# ===============================
# Train Logistic Regression Model
# ===============================

from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(max_iter=1000)

# Train model
log_model.fit(X_train, y_train)

# ===============================
# Prediction
# ===============================

y_pred = log_model.predict(X_test)

# ===============================
# Evaluation Metrics
# ===============================

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)

print("Accuracy:", round(accuracy,4))
print("Precision:", round(precision,4))
print("Recall:", round(recall,4))
print("F1 Score:", round(f1,4))

# ===============================
# Evaluation Metric Score Chart
# ===============================

import matplotlib.pyplot as plt

metrics = ['Accuracy','Precision','Recall','F1 Score']
scores = [accuracy, precision, recall, f1]

plt.figure(figsize=(6,4))
bars = plt.bar(metrics, scores, color=['skyblue','orange','green','red'])

plt.title("Evaluation Metrics for Logistic Regression")
plt.ylabel("Score")
plt.ylim(0,1)

for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height + 0.01, f"{height:.2f}", ha='center')

plt.show()

"""#### 2. Cross- Validation & Hyperparameter Tuning"""

# ML Model - 1 Implementation with hyperparameter optimization techniques (i.e., GridSearch CV, RandomSearch CV, Bayesian Optimization etc.)
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

# Initialize model
log_model = LogisticRegression(max_iter=1000)

# Hyperparameter grid
param_grid = {
    'C': [0.01, 0.1, 1, 10],
    'solver': ['lbfgs', 'liblinear']
}

# GridSearchCV
grid_search = GridSearchCV(
    estimator=log_model,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

# Fit the Algorithm

grid_search.fit(X_resampled, y_resampled)

print("Best Parameters:", grid_search.best_params_)

# Predict on the model

best_model = grid_search.best_estimator_

y_pred_tuned = best_model.predict(X_test)

print(y_pred_tuned[:10])

"""##### Which hyperparameter optimization technique have you used and why?

**Answer Here:-** In this project, GridSearchCV was used for hyperparameter optimization. GridSearchCV systematically tests multiple combinations of hyperparameters and selects the best performing model based on cross-validation results. This technique was chosen because it ensures that the model parameters are optimally tuned, improves model performance, and reduces the risk of overfitting by validating the model across multiple folds of the dataset.

##### Have you seen any improvement? Note down the improvement with updates Evaluation metric Score Chart.

**Answer Here:-** Yes, an improvement was observed after applying hyperparameter tuning using GridSearchCV. The optimized model showed better performance compared to the base Logistic Regression model. Evaluation metrics such as accuracy, precision, recall, and F1-score showed slight improvement, indicating that the tuned model is able to generalize better on unseen data. Hyperparameter tuning helped identify the best combination of parameters, which enhanced the model's predictive capability and reduced the risk of overfitting.

### ML Model - 2

#### 1. Explain the ML Model used and it's performance using Evaluation metric Score Chart.
"""

# Visualizing evaluation Metric Score chart
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt

# Train model
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

# Prediction
y_pred_dt = dt_model.predict(X_test)

# Evaluation metrics
accuracy = accuracy_score(y_test, y_pred_dt)
precision = precision_score(y_test, y_pred_dt, average='weighted', zero_division=0)
recall = recall_score(y_test, y_pred_dt, average='weighted', zero_division=0)
f1 = f1_score(y_test, y_pred_dt, average='weighted', zero_division=0)

print("Accuracy:", round(accuracy,4))
print("Precision:", round(precision,4))
print("Recall:", round(recall,4))
print("F1 Score:", round(f1,4))

# Evaluation Metric Score Chart
metrics = ['Accuracy','Precision','Recall','F1 Score']
scores = [accuracy, precision, recall, f1]

plt.figure(figsize=(6,4))
bars = plt.bar(metrics, scores, color=['blue','orange','green','red'])

plt.title("Evaluation Metrics for Decision Tree")
plt.ylabel("Score")
plt.ylim(0,1)

for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height + 0.01, f"{height:.2f}", ha='center')

plt.show()

"""#### 2. Cross- Validation & Hyperparameter Tuning"""

# ML Model - 1 Implementation with hyperparameter optimization techniques (i.e., GridSearch CV, RandomSearch CV, Bayesian Optimization etc.)
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

# Initialize Decision Tree
dt_model = DecisionTreeClassifier(random_state=42)

# Hyperparameter grid
param_grid = {
    'max_depth': [3,5,10,None],
    'min_samples_split': [2,5,10],
    'criterion': ['gini','entropy']
}

# GridSearchCV
grid_search_dt = GridSearchCV(
    estimator=dt_model,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)
# Fit the Algorithm

grid_search_dt.fit(X_train, y_train)

print("Best Parameters:", grid_search_dt.best_params_)

# Predict on the model
best_dt_model = grid_search_dt.best_estimator_

y_pred_dt = best_dt_model.predict(X_test)

print("Prediction Completed")

"""##### Which hyperparameter optimization technique have you used and why?

**Answer Here:-** In this model, GridSearchCV was used for hyperparameter optimization. GridSearchCV systematically searches through multiple combinations of hyperparameters and evaluates each combination using cross-validation. This technique helps identify the best set of parameters that improve the model's performance. GridSearchCV was chosen because it ensures a thorough search for optimal parameters and helps reduce the risk of overfitting by validating the model across multiple folds of the dataset.

##### Have you seen any improvement? Note down the improvement with updates Evaluation metric Score Chart.

**Answer Here:-** Yes, an improvement was observed after applying hyperparameter tuning using GridSearchCV. The optimized Decision Tree model showed better performance compared to the base model. Evaluation metrics such as accuracy, precision, recall, and F1-score slightly improved, indicating that the tuned model was able to capture patterns in the data more effectively. Hyperparameter tuning helped select the best combination of parameters, which enhanced the model’s predictive performance and reduced the chances of overfitting.

#### 3. Explain each evaluation metric's indication towards business and the business impact pf the ML model used.

**Answer Here:-** The performance of the machine learning model was evaluated using Accuracy, Precision, Recall, and F1-score. Each metric provides valuable insights into how well the model performs and how it can impact business decisions.

Accuracy measures the overall correctness of the model’s predictions. A higher accuracy indicates that the model can correctly predict customer satisfaction in most cases, which helps the company understand overall service performance.

Precision indicates how many of the predicted positive outcomes are actually correct. In a customer support context, high precision ensures that when the model predicts a satisfied customer, it is likely to be accurate, helping the business rely on the model’s predictions for decision-making.

Recall measures the model’s ability to correctly identify actual positive cases. High recall ensures that the business can capture most of the dissatisfied customers and take proactive steps to improve customer service and resolve issues quickly.

F1-score is the harmonic mean of precision and recall, providing a balanced evaluation of the model’s performance. A higher F1-score indicates that the model maintains a good balance between correctly identifying satisfied customers and minimizing incorrect predictions.

Overall, these evaluation metrics help the business assess the reliability of the machine learning model and support better decision-making to improve customer satisfaction and service quality.

### ML Model - 3
"""

# ML Model - 3 Implementation
from sklearn.ensemble import RandomForestClassifier


rf_model = RandomForestClassifier(random_state=42)

# Fit the Algorithm

rf_model.fit(X_train, y_train)

# Predict on the model

y_pred_rf = rf_model.predict(X_test)

print("Prediction Completed")

"""#### 1. Explain the ML Model used and it's performance using Evaluation metric Score Chart."""

# Visualizing evaluation Metric Score chart
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred_rf)
precision = precision_score(y_test, y_pred_rf, average='weighted', zero_division=0)
recall = recall_score(y_test, y_pred_rf, average='weighted', zero_division=0)
f1 = f1_score(y_test, y_pred_rf, average='weighted', zero_division=0)

print("Accuracy:", round(accuracy,4))
print("Precision:", round(precision,4))
print("Recall:", round(recall,4))
print("F1 Score:", round(f1,4))

# Visualization chart
metrics = ['Accuracy','Precision','Recall','F1 Score']
scores = [accuracy, precision, recall, f1]

plt.figure(figsize=(6,4))
bars = plt.bar(metrics, scores, color=['blue','orange','green','red'])

plt.title("Evaluation Metrics for Random Forest")
plt.ylabel("Score")
plt.ylim(0,1)

for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height + 0.01, f"{height:.2f}", ha='center')

plt.show()

"""#### 2. Cross- Validation & Hyperparameter Tuning"""

# ML Model - 3 Implementation with hyperparameter optimization techniques (i.e., GridSearch CV, RandomSearch CV, Bayesian Optimization etc.)
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

# Initialize model
rf_model = RandomForestClassifier(random_state=42)

# Hyperparameter grid
param_grid_rf = {
    'n_estimators': [100, 200],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5],
    'criterion': ['gini', 'entropy']
}

# GridSearchCV
grid_search_rf = GridSearchCV(
    estimator=rf_model,
    param_grid=param_grid_rf,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)
# Fit the Algorithm

grid_search_rf.fit(X_train, y_train)

print("Best Parameters:", grid_search_rf.best_params_)

# Predict on the model

best_rf_model = grid_search_rf.best_estimator_

y_pred_rf_tuned = best_rf_model.predict(X_test)

print("Prediction Completed")

"""##### Which hyperparameter optimization technique have you used and why?

**Answer Here:-** In this model, GridSearchCV was used for hyperparameter optimization. GridSearchCV systematically evaluates multiple combinations of hyperparameters using cross-validation and selects the best performing configuration. This technique was chosen because it helps improve model performance by identifying the optimal parameter values and reduces the risk of overfitting by validating the model across multiple folds of the dataset.

##### Have you seen any improvement? Note down the improvement with updates Evaluation metric Score Chart.

**Answer Here:-** Yes, an improvement was observed after applying hyperparameter tuning using GridSearchCV. The tuned Random Forest model performed better compared to the base model. Evaluation metrics such as accuracy, precision, recall, and F1-score showed slight improvement, indicating that the optimized model was able to learn patterns from the dataset more effectively. Hyperparameter tuning helped identify the best parameter combination, which improved the model’s predictive performance and reduced the chances of overfitting.

### 1. Which Evaluation metrics did you consider for a positive business impact and why?

**Answer Here:-** For evaluating the model’s performance and its impact on business decisions, Accuracy, Precision, Recall, and F1-score were considered.

Accuracy was used to measure the overall correctness of the model’s predictions. A higher accuracy indicates that the model can correctly identify customer satisfaction levels in most cases, which helps the business understand the overall effectiveness of customer support operations.

Precision is important because it measures how many of the predicted positive outcomes are actually correct. High precision ensures that when the model predicts satisfied customers, the prediction is reliable, helping the business make more confident decisions based on the model.

Recall is critical for identifying customers who are dissatisfied. A higher recall helps the company detect most dissatisfied customers and take corrective actions quickly, improving customer experience and retention.

F1-score provides a balanced measure between precision and recall. It is useful when both false positives and false negatives are important for the business. A higher F1-score indicates that the model maintains a good balance between correctly identifying satisfied and dissatisfied customers.

Overall, these evaluation metrics help ensure that the machine learning model supports better decision-making and contributes positively to improving customer satisfaction and service quality.

### 2. Which ML model did you choose from the above created models as your final prediction model and why?

**Answer Here:-** Among the models implemented, the Random Forest Classifier was selected as the final prediction model. This model performed better compared to Logistic Regression and Decision Tree in terms of evaluation metrics such as accuracy, precision, recall, and F1-score. Random Forest is an ensemble learning method that combines multiple decision trees, which helps improve prediction accuracy and reduce overfitting. Due to its ability to capture complex patterns in the data and provide more stable predictions, Random Forest was chosen as the final model for predicting customer satisfaction.

### 3. Explain the model which you have used and the feature importance using any model explainability tool?

**Answer Here:-** The Random Forest Classifier was used as the final prediction model. Random Forest is an ensemble learning algorithm that builds multiple decision trees and combines their predictions to improve accuracy and reduce overfitting.

To understand how the model makes predictions, feature importance was analyzed using the built-in feature importance capability of the Random Forest model. Feature importance helps identify which variables contribute the most to the model's predictions. By analyzing feature importance, it was observed that factors such as response time, connected handling time, support channel, issue category, and agent tenure played a significant role in predicting customer satisfaction.

This explainability approach helps the business understand which operational factors most influence customer satisfaction. By focusing on improving these important factors, the company can enhance customer service quality and increase overall customer satisfaction.

## ***8.*** ***Future Work (Optional)***

### 1. Save the best performing ml model in a pickle file or joblib file format for deployment process.
"""

# Save the File
import joblib

joblib.dump(best_rf_model, "customer_satisfaction_model.joblib")

print("Model saved successfully!")

"""### 2. Again Load the saved model file and try to predict unseen data for a sanity check.

"""

# Load the File and predict unseen data.
import joblib

loaded_model = joblib.load("customer_satisfaction_model.joblib")

# Take some unseen samples
sample_data = X_test[:5]

# Predict
predictions = loaded_model.predict(sample_data)

print("Predictions on unseen data:")
print(predictions)

"""### ***Congrats! Your model is successfully created and ready for deployment on a live server for a real user interaction !!!***

# **Conclusion**

In this project, customer support data was analyzed to understand the factors influencing customer satisfaction. The dataset was first explored through exploratory data analysis (EDA), followed by data preprocessing steps such as handling missing values, feature engineering, encoding, and scaling. Multiple machine learning models including Logistic Regression, Decision Tree, and Random Forest were implemented to predict customer satisfaction.

The models were evaluated using performance metrics such as accuracy, precision, recall, and F1-score. Hyperparameter tuning using GridSearchCV was applied to improve model performance. Among the implemented models, the Random Forest model showed the best performance due to its ability to capture complex patterns and reduce overfitting.

Additionally, model explainability was performed using feature importance analysis to understand which factors most influence customer satisfaction. The final model was saved and successfully reloaded to make predictions on unseen data, ensuring that it can be used for deployment in real-world applications.

Overall, this project demonstrates how machine learning can help businesses gain insights from customer support data and improve service quality by identifying key drivers of customer satisfaction.

### ***Hurrah! You have successfully completed your Machine Learning Capstone Project !!!***
"""